enum CameraOrGallery {
  camera,
  gallery,
}

class PhotoMemo {
  String? docId; // generated by Firestore
  String createdBy; // email
  String title;
  String memo;
  String photoFilename;
  String photoURL; // given by Storage
  DateTime? timestamp;
  late List<dynamic> sharedWith;

  PhotoMemo({
    this.docId,
    required this.createdBy,
    required this.memo,
    required this.title,
    required this.photoFilename,
    required this.photoURL,
    this.timestamp,
    List<dynamic>? sharedWith,
  }) {
    this.sharedWith = sharedWith == null ? [] : [...sharedWith];
  }
}
